import { Restaurant } from "@/types/Restaurant";

export const restaurants: Restaurant[] = [
  {
    id: "205961",
    image: "https://images.pexels.com/photos/205961/pexels-photo-205961.jpeg",
    logo: "https://images.pexels.com/photos/1239291/pexels-photo-1239291.jpeg",
    name: "Italian Heaven",
    owner: "Alonzo Krajcik",
    status: "active",
    rating: 4.5,
    reviewCount: 214,
    bgColor: "#F5F5FF",
    city: "Collingwood, Ontario",
    specialties: ["Italian", "Pasta", "Wine"],
    description:
      "Authentic Italian cuisine with a modern twist, featuring classic dishes from the heart of Italy.",
    address: "123 Pasta Lane, Flavor Town",
    phone: "123-456-7890",
    location: {
      latitude: 41.902782,
      longitude: 12.496366,
    },
    information: {
      opening_hours: "11:00 AM - 10:00 PM",
      website: "https://italianheaven.com",
      social_media: {
        facebook: "https://facebook.com/italianheaven",
        instagram: "https://instagram.com/italianheaven",
      },
    },
    menu: [
      {
        category: "Main Course",
        items: [
          {
            id: "101",
            name: "Margherita Pizza",
            description:
              "Classic pizza topped with fresh mozzarella, tomatoes, and basil.",
            price: 12.99,
            quantity: 0,
            availability: true,
            image:
              "https://images.pexels.com/photos/3682837/pexels-photo-3682837.jpeg",
            information: {
              calories: 680,
              allergens: ["Dairy", "Gluten"],
              preparation_time: "15 minutes",
            },
          },
          {
            id: "103",
            name: "Margherita Pizza",
            description:
              "Classic pizza topped with fresh mozzarella, tomatoes, and basil.",
            price: 12.99,
            quantity: 0,
            availability: true,
            image:
              "https://images.pexels.com/photos/3682837/pexels-photo-3682837.jpeg",
            information: {
              calories: 680,
              allergens: ["Dairy", "Gluten"],
              preparation_time: "15 minutes",
            },
          },
          {
            id: "104",
            name: "Margherita Pizza",
            description:
              "Classic pizza topped with fresh mozzarella, tomatoes, and basil.",
            price: 12.99,
            quantity: 0,
            availability: true,
            image:
              "https://images.pexels.com/photos/3682837/pexels-photo-3682837.jpeg",
            information: {
              calories: 680,
              allergens: ["Dairy", "Gluten"],
              preparation_time: "15 minutes",
            },
          },
          {
            id: "102",
            name: "Spaghetti Carbonara",
            description:
              "Traditional spaghetti with a creamy egg and pancetta sauce.",
            price: 13.99,
            quantity: 0,
            availability: true,
            image:
              "https://images.pexels.com/photos/725990/pexels-photo-725990.jpeg",
            information: {
              calories: 720,
              allergens: ["Dairy", "Egg", "Gluten"],
              preparation_time: "20 minutes",
            },
          },
        ],
      },
      {
        category: "Bubble teas",
        items: [
          {
            id: "401",
            name: "Margherita Pizza",
            description:
              "Classic pizza topped with fresh mozzarella, tomatoes, and basil.",
            price: 12.99,
            quantity: 0,
            availability: true,
            image:
              "https://images.pexels.com/photos/3682837/pexels-photo-3682837.jpeg",
            information: {
              calories: 680,
              allergens: ["Dairy", "Gluten"],
              preparation_time: "15 minutes",
            },
          },
          {
            id: "403",
            name: "Margherita Pizza",
            description:
              "Classic pizza topped with fresh mozzarella, tomatoes, and basil.",
            price: 12.99,
            quantity: 0,
            availability: true,
            image:
              "https://images.pexels.com/photos/3682837/pexels-photo-3682837.jpeg",
            information: {
              calories: 680,
              allergens: ["Dairy", "Gluten"],
              preparation_time: "15 minutes",
            },
          },
          {
            id: "404",
            name: "Margherita Pizza",
            description:
              "Classic pizza topped with fresh mozzarella, tomatoes, and basil.",
            price: 12.99,
            quantity: 0,
            availability: true,
            image:
              "https://images.pexels.com/photos/3682837/pexels-photo-3682837.jpeg",
            information: {
              calories: 680,
              allergens: ["Dairy", "Gluten"],
              preparation_time: "15 minutes",
            },
          },
          {
            id: "402",
            name: "Spaghetti Carbonara",
            description:
              "Traditional spaghetti with a creamy egg and pancetta sauce.",
            price: 13.99,
            quantity: 0,
            availability: true,
            image:
              "https://images.pexels.com/photos/725990/pexels-photo-725990.jpeg",
            information: {
              calories: 720,
              allergens: ["Dairy", "Egg", "Gluten"],
              preparation_time: "20 minutes",
            },
          },
        ],
      },
      {
        category: "Boissons",
        items: [
          {
            id: "5101",
            name: "Margherita Pizza",
            description:
              "Classic pizza topped with fresh mozzarella, tomatoes, and basil.",
            price: 12.99,
            quantity: 0,
            availability: true,
            image:
              "https://images.pexels.com/photos/3682837/pexels-photo-3682837.jpeg",
            information: {
              calories: 680,
              allergens: ["Dairy", "Gluten"],
              preparation_time: "15 minutes",
            },
          },
          {
            id: "5103",
            name: "Margherita Pizza",
            description:
              "Classic pizza topped with fresh mozzarella, tomatoes, and basil.",
            price: 12.99,
            quantity: 0,
            availability: true,
            image:
              "https://images.pexels.com/photos/3682837/pexels-photo-3682837.jpeg",
            information: {
              calories: 680,
              allergens: ["Dairy", "Gluten"],
              preparation_time: "15 minutes",
            },
          },
          {
            id: "5104",
            name: "Margherita Pizza",
            description:
              "Classic pizza topped with fresh mozzarella, tomatoes, and basil.",
            price: 12.99,
            quantity: 0,
            availability: true,
            image:
              "https://images.pexels.com/photos/3682837/pexels-photo-3682837.jpeg",
            information: {
              calories: 680,
              allergens: ["Dairy", "Gluten"],
              preparation_time: "15 minutes",
            },
          },
          {
            id: "5102",
            name: "Spaghetti Carbonara",
            description:
              "Traditional spaghetti with a creamy egg and pancetta sauce.",
            price: 13.99,
            quantity: 0,
            availability: true,
            image:
              "https://images.pexels.com/photos/725990/pexels-photo-725990.jpeg",
            information: {
              calories: 720,
              allergens: ["Dairy", "Egg", "Gluten"],
              preparation_time: "20 minutes",
            },
          },
        ],
      },
      {
        category: "Desserts",
        items: [
          {
            id: "201",
            name: "Tiramisu",
            description:
              "Layered dessert with coffee-soaked ladyfingers, mascarpone cheese, and cocoa.",
            price: 6.99,
            quantity: 0,
            availability: true,
            image:
              "https://images.pexels.com/photos/4078174/pexels-photo-4078174.jpeg",
            information: {
              calories: 450,
              allergens: ["Dairy", "Gluten"],
              preparation_time: "10 minutes",
            },
          },
          {
            id: "202",
            name: "Panna Cotta",
            description: "Creamy custard served with a berry compote.",
            price: 7.99,
            quantity: 0,
            availability: true,
            image:
              "https://images.pexels.com/photos/302468/pexels-photo-302468.jpeg",
            information: {
              calories: 350,
              allergens: ["Dairy"],
              preparation_time: "15 minutes",
            },
          },
        ],
      },
      {
        category: "Cocktails",
        items: [
          {
            id: "301",
            name: "Tiramisu",
            description:
              "Layered dessert with coffee-soaked ladyfingers, mascarpone cheese, and cocoa.",
            price: 6.99,
            quantity: 0,
            availability: true,
            image:
              "https://images.pexels.com/photos/4078174/pexels-photo-4078174.jpeg",
            information: {
              calories: 450,
              allergens: ["Dairy", "Gluten"],
              preparation_time: "10 minutes",
            },
          },
          {
            id: "302",
            name: "Panna Cotta",
            description: "Creamy custard served with a berry compote.",
            price: 7.99,
            quantity: 0,
            availability: true,
            image:
              "https://images.pexels.com/photos/302468/pexels-photo-302468.jpeg",
            information: {
              calories: 350,
              allergens: ["Dairy"],
              preparation_time: "15 minutes",
            },
          },
        ],
      },
    ],
  },
  {
    id: "958545",
    image: "https://images.pexels.com/photos/958545/pexels-photo-958545.jpeg",
    logo: "https://images.pexels.com/photos/1239291/pexels-photo-1239291.jpeg",
    name: "Sushi Place",
    owner: "Franklin Rolfson",
    status: "active",
    rating: 4.7,
    reviewCount: 214,
    bgColor: "#DEE8FF",
    city: "Collingwood, Ontario",
    specialties: ["Japanese", "Sushi", "Seafood"],
    description:
      "Experience the art of sushi making with our expert chefs, offering a wide variety of fresh and creative sushi rolls.",
    address: "456 Fish Street, Ocean City",
    phone: "234-567-8901",
    location: {
      latitude: 35.689487,
      longitude: 139.691711,
    },
    information: {
      opening_hours: "12:00 PM - 11:00 PM",
      website: "https://sushiworld.com",
      social_media: {
        facebook: "https://facebook.com/sushiworld",
        instagram: "https://instagram.com/sushiworld",
      },
    },
    menu: [
      {
        category: "Sushi",
        items: [
          {
            id: "3011",
            name: "Dragon Roll",
            description:
              "Shrimp tempura and avocado roll topped with eel and sweet sauce.",
            price: 15.99,
            quantity: 0,
            availability: true,
            image: "https://example.com/images/dragon_roll.jpg",
            information: {
              calories: 450,
              allergens: ["Seafood", "Soy"],
              preparation_time: "10 minutes",
            },
          },
          {
            id: "3022",
            name: "Salmon Nigiri",
            description: "Slices of fresh salmon over sushi rice.",
            price: 8.99,
            quantity: 0,
            availability: true,
            image: "https://example.com/images/salmon_nigiri.jpg",
            information: {
              calories: 250,
              allergens: ["Seafood"],
              preparation_time: "5 minutes",
            },
          },
        ],
      },
      {
        category: "Appetizers",
        items: [
          {
            id: "4011",
            name: "Edamame",
            description: "Steamed and salted soybeans.",
            price: 4.99,
            quantity: 0,
            availability: true,
            image: "https://example.com/images/edamame.jpg",
            information: {
              calories: 200,
              allergens: ["Soy"],
              preparation_time: "5 minutes",
            },
          },
          {
            id: "4022",
            name: "Gyoza",
            description: "Pan-fried dumplings with a savory pork filling.",
            price: 6.99,
            quantity: 0,
            availability: true,
            image: "https://example.com/images/gyoza.jpg",
            information: {
              calories: 300,
              allergens: ["Pork", "Gluten"],
              preparation_time: "10 minutes",
            },
          },
        ],
      },
    ],
  },
  {
    id: "260922",
    image: "https://images.pexels.com/photos/260922/pexels-photo-260922.jpeg",
    logo: "https://images.pexels.com/photos/1239291/pexels-photo-1239291.jpeg",
    name: "Taco Fiesta",
    owner: "Kerry Beier",
    status: "active",
    rating: 4.8,
    reviewCount: 214,
    bgColor: "#F5F5FF",
    city: "Collingwood, Ontario",
    specialties: ["Mexican"],
    description:
      "Vibrant Mexican eatery specializing in a variety of tacos and traditional Mexican dishes.",
    address: "789 Fiesta Road, Spice City",
    phone: "345-678-9012",
    location: {
      latitude: 19.432608,
      longitude: -99.133209,
    },
    information: {
      opening_hours: "10:00 AM - 10:00 PM",
      website: "https://tacofiesta.com",
      social_media: {
        facebook: "https://facebook.com/tacofiesta",
        instagram: "https://instagram.com/tacofiesta",
      },
    },
    menu: [
      {
        category: "Tacos",
        items: [
          {
            id: "501",
            name: "Tacos Al Pastor",
            description: "Marinated pork tacos with pineapple and cilantro.",
            price: 9.99,
            quantity: 0,
            availability: true,
            image: "https://example.com/images/tacos_al_pastor.jpg",
            information: {
              calories: 350,
              allergens: ["Pork"],
              preparation_time: "10 minutes",
            },
          },
          {
            id: "502",
            name: "Fish Tacos",
            description: "Grilled fish tacos with a zesty slaw.",
            price: 11.99,
            quantity: 0,
            availability: true,
            image: "https://example.com/images/fish_tacos.jpg",
            information: {
              calories: 400,
              allergens: ["Seafood"],
              preparation_time: "12 minutes",
            },
          },
        ],
      },
      {
        category: "Sides",
        items: [
          {
            id: "601",
            name: "Guacamole",
            description: "Fresh avocado dip with lime and cilantro.",
            price: 5.99,
            quantity: 0,
            availability: true,
            image: "https://example.com/images/guacamole.jpg",
            information: {
              calories: 250,
              preparation_time: "5 minutes",
            },
          },
          {
            id: "602",
            name: "Chips and Salsa",
            description: "Crispy tortilla chips served with house-made salsa.",
            price: 3.99,
            quantity: 0,
            availability: true,
            image: "https://example.com/images/chips_salsa.jpg",
            information: {
              calories: 300,
              preparation_time: "5 minutes",
            },
          },
        ],
      },
    ],
  },
  {
    id: "2290753",
    image: "https://images.pexels.com/photos/2290753/pexels-photo-2290753.jpeg",
    logo: "https://images.pexels.com/photos/1239291/pexels-photo-1239291.jpeg",
    name: "Burger Joint",
    description:
      "Gourmet burgers made with the finest ingredients and creative toppings, served in a cozy atmosphere.",
    owner: "Lyle Schmeler",
    status: "active",
    rating: 4.2,
    reviewCount: 214,
    bgColor: "#F0F5F7",
    city: "Collingwood, Ontario",
    specialties: ["American"],
    address: "101 Burger Boulevard, Flavor Town",
    phone: "456-789-0123",
    location: {
      latitude: 40.712776,
      longitude: -74.005974,
    },
    information: {
      opening_hours: "10:00 AM - 10:00 PM",
      website: "https://Burger-joint.com",
      social_media: {
        facebook: "https://facebook.com/Burger-joint",
        instagram: "https://instagram.com/Burger-joint",
      },
    },
    menu: [
      {
        category: "Burgers",
        items: [
          {
            id: "701",
            name: "Classic Cheeseburger",
            description:
              "Juicy beef patty with cheddar cheese, lettuce, tomato, and pickles.",
            price: 10.99,
            quantity: 0,
            availability: true,
            image: "https://example.com/images/classic_cheeseburger.jpg",
          },
          {
            id: "702",
            name: "BBQ Bacon Burger",
            description:
              "Beef burger topped with bacon, cheddar, and BBQ sauce.",
            price: 12.99,
            quantity: 0,
            availability: true,
            image: "https://example.com/images/bbq_bacon_burger.jpg",
          },
        ],
      },
      {
        category: "Sides",
        items: [
          {
            id: "801",
            name: "French Fries",
            description: "Crispy golden fries served with ketchup.",
            price: 3.99,
            quantity: 0,
            availability: true,
            image: "https://example.com/images/french_fries.jpg",
          },
          {
            id: "802",
            name: "Onion Rings",
            description: "Crispy onion rings with a side of ranch dressing.",
            price: 4.99,
            quantity: 0,
            availability: true,
            image: "https://example.com/images/onion_rings.jpg",
          },
        ],
      },
    ],
  },
  {
    id: "1383776",
    image: "https://images.pexels.com/photos/1383776/pexels-photo-1383776.jpeg",
    logo: "https://images.pexels.com/photos/1239291/pexels-photo-1239291.jpeg",
    name: "Chinese Dragon",
    owner: "Maurice Kertzmann MD",
    status: "active",
    rating: 4.8,
    reviewCount: 214,
    bgColor: "#F3EFF9",
    city: "Collingwood, Ontario",
    specialties: ["Chinese"],
    description:
      "Explore a diverse range of Chinese dishes, from traditional favorites to modern interpretations.",
    address: "202 Noodle Street, Flavor Town",
    phone: "567-890-1234",
    location: {
      latitude: 39.904202,
      longitude: 116.407394,
    },
    menu: [
      {
        category: "Main Course",
        items: [
          {
            id: "901",
            name: "Kung Pao Chicken",
            description: "Stir-fried chicken with peanuts and chili peppers.",
            price: 13.99,
            quantity: 0,
            availability: true,
            image: "https://example.com/images/kung_pao_chicken.jpg",
          },
          {
            id: "902",
            name: "Sweet and Sour Pork",
            description: "Pork in a sweet and tangy sauce with pineapple.",
            price: 12.99,
            quantity: 0,
            availability: true,
            image: "https://example.com/images/sweet_sour_pork.jpg",
          },
        ],
      },
    ],
  },
];

export const couriers = [
  {
    id: "CR001",
    name: "John Doe",
    status: "active",
    rating: 4.8,
    reviewCount: 150,
    totalDeliveries: 1200,
    registeredAt: "2024-01-06",
    vehicle: "Bicycle",
    phone: "123-456-789",
    email: "john.doe@example.com",
    lastDelivery: "2024-08-25 14:35",
    city: "New York",
    availableFrom: "08:00",
    availableTo: "20:00",
    licensePlate: "X8TRDJ0JTBTB98469",
    totalEarnings: 574.9,
  },
  {
    id: "CR002",
    name: "Jane Smith",
    status: "on delivery",
    rating: 4.6,
    reviewCount: 98,
    totalDeliveries: 950,
    registeredAt: "2024-07-24",
    vehicle: "Motorcycle",
    phone: "987-654-321",
    email: "jane.smith@example.com",
    lastDelivery: "2024-08-25 14:45",
    city: "Los Angeles",
    availableFrom: "10:00",
    availableTo: "22:00",
    licensePlate: "8Y6FTUT4PTPP89664",
    totalEarnings: 289.54,
  },
  {
    id: "CR003",
    name: "Michael Johnson",
    status: "available",
    rating: 4.9,
    reviewCount: 200,
    totalDeliveries: 1500,
    registeredAt: "2024-08-13",
    vehicle: "Car",
    phone: "456-789-123",
    email: "michael.johnson@example.com",
    lastDelivery: "2024-08-25 12:30",
    city: "Chicago",
    availableFrom: "09:00",
    availableTo: "21:00",
    licensePlate: "MG9D0E7N21E943270",
    totalEarnings: 470.33,
  },
  {
    id: "CR004",
    name: "Emily Davis",
    status: "offline",
    rating: 4.7,
    reviewCount: 80,
    totalDeliveries: 700,
    registeredAt: "2024-02-06",
    vehicle: "Scooter",
    phone: "321-654-987",
    email: "emily.davis@example.com",
    lastDelivery: "2024-08-24 18:15",
    city: "Houston",
    availableFrom: "07:00",
    availableTo: "17:00",
    licensePlate: "HU56MN3Z8VU130319",
    totalEarnings: 963.17,
  },
  {
    id: "CR005",
    name: "Chris Brown",
    status: "on break",
    rating: 4.5,
    reviewCount: 60,
    totalDeliveries: 550,
    registeredAt: "2024-06-13",
    vehicle: "Bicycle",
    phone: "789-123-456",
    email: "chris.brown@example.com",
    lastDelivery: "2024-08-25 13:00",
    city: "Miami",
    availableFrom: "08:00",
    availableTo: "18:00",
    licensePlate: "GNW7KKY5SDDN37535",
    totalEarnings: 243.72,
  },
  {
    id: "CR006",
    name: "Sarah Wilson",
    status: "active",
    rating: 4.8,
    reviewCount: 140,
    totalDeliveries: 1100,
    registeredAt: "2024-03-26",
    vehicle: "Motorcycle",
    phone: "654-321-789",
    email: "sarah.wilson@example.com",
    lastDelivery: "2024-08-25 14:20",
    city: "San Francisco",
    availableFrom: "08:00",
    availableTo: "20:00",
    licensePlate: "XHV7PXGSR9KP35961",
    totalEarnings: 597.63,
  },
  {
    id: "CR007",
    name: "David Lee",
    status: "available",
    rating: 4.9,
    reviewCount: 170,
    totalDeliveries: 1300,
    registeredAt: "2024-06-22",
    vehicle: "Car",
    phone: "159-753-486",
    email: "david.lee@example.com",
    lastDelivery: "2024-08-25 12:00",
    city: "Seattle",
    availableFrom: "09:00",
    availableTo: "21:00",
    licensePlate: "Z6UE4F0XHJDU32464",
    totalEarnings: 438.29,
  },
  {
    id: "CR008",
    name: "Laura Miller",
    status: "on delivery",
    rating: 4.6,
    reviewCount: 120,
    totalDeliveries: 1000,
    registeredAt: "2023-11-18",
    vehicle: "Scooter",
    phone: "852-963-741",
    email: "laura.miller@example.com",
    lastDelivery: "2024-08-25 14:50",
    city: "Boston",
    availableFrom: "10:00",
    availableTo: "22:00",
    licensePlate: "RT4H3CPW7UNL25555",
    totalEarnings: 941.64,
  },
  {
    id: "CR009",
    name: "James Anderson",
    status: "active",
    rating: 4.7,
    reviewCount: 105,
    totalDeliveries: 800,
    registeredAt: "2024-01-07",
    vehicle: "Bicycle",
    phone: "951-357-258",
    email: "james.anderson@example.com",
    lastDelivery: "2024-08-25 13:15",
    city: "Dallas",
    availableFrom: "07:00",
    availableTo: "19:00",
    licensePlate: "73BWWM6T73TR37856",
    totalEarnings: 210.97,
  },
  {
    id: "CR010",
    name: "Sophia Thompson",
    status: "offline",
    rating: 4.4,
    reviewCount: 55,
    totalDeliveries: 500,
    registeredAt: "2023-12-02",
    vehicle: "Motorcycle",
    phone: "357-258-951",
    email: "sophia.thompson@example.com",
    lastDelivery: "2024-08-24 17:45",
    city: "Philadelphia",
    availableFrom: "08:00",
    availableTo: "18:00",
    licensePlate: "V1RWGW8EESV262520",
    totalEarnings: 307.85,
  },
];

export const orders = [
  {
    id: "ORD001",
    restaurantId: "REST001",
    restaurantName: "Gourmet Palace",
    restaurantPhone: "942-535-8771",
    customerId: "CUST001",
    customerName: "Alice Johnson",
    customerAddress: "123 Main St, New York, NY",
    customerPhone: "123-456-789",
    courierId: "CR001",
    courierName: "John Doe",
    status: "delivered",
    totalAmount: 45.99,
    orderDate: "2024-08-25 12:30",
    deliveryDate: "2024-08-25 13:00",
    items: [
      {
        itemName: "Grilled Chicken",
        quantity: 2,
        price: 15.99,
      },
      {
        itemName: "Caesar Salad",
        quantity: 1,
        price: 9.99,
      },
    ],
    paymentMethod: "Credit Card",
    deliveryFee: 5.0,
    rating: 5,
  },
  {
    id: "ORD002",
    restaurantId: "REST002",
    restaurantName: "Pizza Haven",
    restaurantPhone: "522-350-5881",
    customerId: "CUST002",
    customerName: "Bob Smith",
    customerAddress: "456 Elm St, Los Angeles, CA",
    customerPhone: "987-654-321",
    courierId: "CR002",
    courierName: "Jane Smith",
    status: "on the way",
    totalAmount: 30.75,
    orderDate: "2024-08-25 12:45",
    deliveryDate: null,
    items: [
      {
        itemName: "Pepperoni Pizza",
        quantity: 1,
        price: 18.75,
      },
      {
        itemName: "Garlic Bread",
        quantity: 1,
        price: 6.0,
      },
      {
        itemName: "Soda",
        quantity: 1,
        price: 6.0,
      },
    ],
    paymentMethod: "PayPal",
    deliveryFee: 4.0,
    rating: null,
  },
  {
    id: "ORD003",
    restaurantId: "REST003",
    restaurantName: "Burger World",
    restaurantPhone: "962-814-9895",
    customerId: "CUST003",
    customerName: "Charlie Davis",
    customerAddress: "789 Pine St, Chicago, IL",
    customerPhone: "456-789-123",
    courierId: "CR003",
    courierName: "Michael Johnson",
    status: "preparing",
    totalAmount: 25.5,
    orderDate: "2024-08-25 12:55",
    deliveryDate: null,
    items: [
      {
        itemName: "Cheeseburger",
        quantity: 2,
        price: 10.5,
      },
      {
        itemName: "Fries",
        quantity: 2,
        price: 4.5,
      },
    ],
    paymentMethod: "Cash",
    deliveryFee: 3.5,
    rating: null,
  },
  {
    id: "ORD004",
    restaurantId: "REST004",
    restaurantName: "Sushi Central",
    restaurantPhone: "512-971-9838",
    customerId: "CUST004",
    customerName: "Diane Evans",
    customerAddress: "101 Maple St, Houston, TX",
    customerPhone: "321-654-987",
    courierId: "CR004",
    courierName: "Emily Davis",
    status: "cancelled",
    totalAmount: 50.25,
    orderDate: "2024-08-25 13:00",
    deliveryDate: null,
    items: [
      {
        itemName: "Salmon Sushi",
        quantity: 3,
        price: 16.75,
      },
      {
        itemName: "Tuna Roll",
        quantity: 2,
        price: 14.5,
      },
    ],
    paymentMethod: "Credit Card",
    deliveryFee: 5.0,
    rating: null,
  },
  {
    id: "ORD005",
    restaurantId: "REST005",
    restaurantName: "Taco Fiesta",
    restaurantPhone: "667-523-4795",
    customerId: "CUST005",
    customerName: "Eve Foster",
    customerAddress: "202 Oak St, Miami, FL",
    customerPhone: "789-123-456",
    courierId: "CR005",
    courierName: "Chris Brown",
    status: "delivered",
    totalAmount: 22.0,
    orderDate: "2024-08-25 13:10",
    deliveryDate: "2024-08-25 13:45",
    items: [
      {
        itemName: "Chicken Tacos",
        quantity: 2,
        price: 9.0,
      },
      {
        itemName: "Churros",
        quantity: 1,
        price: 4.0,
      },
    ],
    paymentMethod: "Apple Pay",
    deliveryFee: 3.0,
    rating: 4,
  },
];

export const customers = [
  {
    id: "CUST001",
    name: "John Doe",
    email: "johndoe@example.com",
    phone: "123-456-789",
    address: "123 Main St, Springfield, USA",
    city: "Springfield",
    postalCode: "12345",
    country: "USA",
    registeredAt: "2023-05-15",
    lastOrderDate: "2023-08-21",
    totalOrders: 25,
    totalSpent: 1250.5,
    loyaltyPoints: 350,
    status: "active", // Active, Inactive, Banned, etc.
  },
  {
    id: "CUST002",
    name: "Jane Smith",
    email: "janesmith@example.com",
    phone: "987-654-321",
    address: "456 Elm St, Metropolis, USA",
    city: "Metropolis",
    postalCode: "67890",
    country: "USA",
    registeredAt: "2022-10-20",
    lastOrderDate: "2023-08-10",
    totalOrders: 40,
    totalSpent: 2000.75,
    loyaltyPoints: 500,
    status: "active",
  },
  {
    id: "CUST003",
    name: "Alice Johnson",
    email: "alicej@example.com",
    phone: "555-123-456",
    address: "789 Oak St, Gotham, USA",
    city: "Gotham",
    postalCode: "13579",
    country: "USA",
    registeredAt: "2023-02-15",
    lastOrderDate: "2023-07-30",
    totalOrders: 12,
    totalSpent: 600.3,
    loyaltyPoints: 200,
    status: "inactive",
  },
  {
    id: "CUST004",
    name: "Bob Brown",
    email: "bobbrown@example.com",
    phone: "321-654-987",
    address: "101 Maple St, Star City, USA",
    city: "Star City",
    postalCode: "24680",
    country: "USA",
    registeredAt: "2021-07-10",
    lastOrderDate: "2023-07-28",
    totalOrders: 50,
    totalSpent: 3000.0,
    loyaltyPoints: 750,
    status: "banned",
  },
  {
    id: "CUST005",
    name: "Charlie Davis",
    email: "charlied@example.com",
    phone: "789-012-345",
    address: "202 Birch St, Central City, USA",
    city: "Central City",
    postalCode: "54321",
    country: "USA",
    registeredAt: "2023-01-05",
    lastOrderDate: "2023-08-01",
    totalOrders: 18,
    totalSpent: 900.6,
    loyaltyPoints: 275,
    status: "active",
  },
];

export const promotions = [
  {
    id: 1,
    image: "/promo1.jpg",
    title: "Summer Sale!",
    description: "Up to 50% off on all items.",
    link: "/promo/summer-sale",
  },
  {
    id: 2,
    image: "/promo2.jpg",
    title: "Buy 1 Get 1 Free!",
    description: "Limited time offer on select items.",
    link: "/promo/bogo",
  },
  {
    id: 3,
    image: "/promo3.jpg",
    title: "Exclusive Member Discounts",
    description: "Sign up today to enjoy exclusive perks.",
    link: "/promo/members",
  },
  {
    id: 4,
    image: "/promo4.jpg",
    title: "Exclusive Member Discounts",
    description: "Sign up today to enjoy exclusive perks.",
    link: "/promo/members",
  },
];
